Add support for basic group functions in the query endpoint.
GetDKAN/dkan pull request #3509
Opened 2021-06-05 00:51 UTC by dharizza

fixes #3480 

## QA Steps

- [ ] Go to the query endpoint and try to add an expression with group functions like SUM, AVG, COUNT, MIN or MAX, results should be correct. The URL may look similar to this `api/1/datastore/query/DATASTORE_UUID?properties[0][alias]=test&properties[0][expression][operator]=SUM&properties[0][expression][operands][]=COLUMN_NAME`. The JSON object for this expression follows the following pattern:
```
{
  "properties": [
    {
      "alias": "test",
      "expression": {
        "operator": "SUM",
        "operands": ["COLUMN_NAME"]
      }
    }
  ]
}

2021-06-05 19:58 UTC, dafeder requested changes
So, this was fairly easy for me to break, just adding an additional property like "record_number" results in a return of "Database internal error". 

I think we need to either: a) do some validation in the schema or the processing code to catch things that are obviously going to break something, or b) see whether we have enough information in the exception we throw in `AbstractDatabaseTable::query()` to give the user better feedback/guidance. I'm pretty sure the issue is just mixing an multi-row column with an aggregation column and not providing a GROUP BY clause. 

So, if the error we get is specific enough to detect this, maybe use the `sanitizedErrorMessage()` method to say something like, "you may not mix simple properties and aggregation expressions in a single query. If one of your properties includes an expression with a sum, count, avg, min or max operator, remove other properties from your query and try again."

2021-06-05 19:58 UTC, dafeder commented on modules/datastore/docs/query.json
> +                        "%",
@dharizza in the rest of the schema the convention has been to use lowercase, let's do that here and convert to upper in one of the factories if necessary.

2021-06-09 16:36 UTC, dafeder commented
Updated PR description to use lower-case operators

2021-06-09 20:05 UTC, dafeder approved these changes

2021-06-09 20:27 UTC, klimp-drupal approved these changes

2021-06-09 23:26 UTC, merged