By default trigger datastore update when dataset modified date changes
GetDKAN/dkan pull request #3554
Opened 2021-07-10 22:04 UTC by dharizza

fixes #3552 

## QA Steps

- [ ] Go to admin/dkan/datastore and set the field you want as the datastore triggering property.
- [ ] Create a new dataset and confirm it is imported to the datastore.
- [ ] Edit your dataset and update the value for the field you chose in step 1 (by default we use the Last Update - modified date), save the dataset.
- [ ] Confirm the datastore is updated.

2021-07-15 17:44 UTC, dafeder commented
Need test coverage for `retrieveSchemaProperties()`

2021-07-21 21:54 UTC, dafeder requested changes
@dharizza after QAing realized we should have thought more about the form specifics -- let's make that small change before shipping this.

2021-07-21 21:54 UTC, dafeder commented on modules/datastore/src/EventSubscriber/DatastoreSubscriber.php
> +    $field = $field ? $field : 'modified';
Let's avoid hard-coding "modified" here. I know the issue suggested otherwise but realizing this should just default to nothing.

2021-07-21 21:54 UTC, dafeder commented on modules/datastore/src/Form/DatastoreSettingsForm.php
> +      '#type' => 'select',
This should have been specified in the ticket, but after QAing this I think it's clear that this should be checkboxes with the ability to have multiple or no fields chosen.

2021-07-26 14:26 UTC, janette commented
Add option for none,
test for none option

2021-07-28 18:29 UTC, clayliddell commented
The 1 issue that CodeClimate is complaining about is not possible to resolve without triggering another CodeClimate error... Not sure how to proceed.

2021-07-29 21:12 UTC, dafeder commented
@clayliddell we have the ability to approve a PR through code climate despite having a warning -- we do this often for constructors because the dependency injection technique often leads to this issue.

On QA I'm seeing strange behavior when testing having no property checked. I create a dataset and then update the modified date. Despite not having any property checked, I am seeing a new distribution created and a new datastore_import job in the queue. When I run the queue I get to a strange state where the dataset no longer appears in the catalog (it's gone from api/1/metastore/schemas/dataset/items). Inspecting the JSON it looks like in the new distribution that was created, the downloadUrl was simply left blank. 

I think it is working as expected with "modified" checked.

2021-08-09 19:26 UTC, dafeder approved these changes

2021-08-09 19:27 UTC, dafeder commented
Jenkins failure is a CI server problem, build is fine.

2021-08-09 19:28 UTC, dafeder commented
I am seeing a resource_purger job created after patching a dataset with nothing checked, which probably shouldn't happen. But, I do not see any ill effects from this.

2021-08-09 19:28 UTC, merged