3365 local file trasher option
GetDKAN/dkan pull request #3563
Opened 2021-07-16 19:05 UTC by klimp-drupal

fixes [org/repo/issue#]

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

2021-07-16 20:37 UTC, klimp-drupal commented
local file. The resource folder is empty but doesn't get deleted `docroot/sites/default/files/resources/f7728135a2b783904a13b1d2dd0f1d4d_1626467168/` . For the remote file it gets deleted

2021-07-16 20:38 UTC, klimp-drupal commented
remote file. The filefetcher record doesn't get deleted (It does for the local file)

2021-09-07 17:52 UTC, clayliddell requested changes

2021-09-07 17:52 UTC, clayliddell commented on modules/datastore/src/Plugin/QueueWorker/Import.php
> +      if ($this->container->get('config.factory')->get('datastore.settings')->get('delete_local_resource')) {
We should be using dependency injection here, instead of fetching the config factory at the last minute from the container. That would allow us to more easily overwrite the "delete_local_resource" setting in tests.

2021-09-07 19:44 UTC, clayliddell approved these changes

2021-09-07 19:51 UTC, clayliddell commented
The changes in this PR take care of imported resource files left in the `/resources` directory, but not abandonded resource files left in the `/uploaded_resources` directory (i.e. in the case of a distribution being deleted, or of a distribution file being replaced).

2021-09-08 20:14 UTC, merged