Save new distribution version when MIME type changes
GetDKAN/dkan pull request #3614
Opened 2021-08-11 00:53 UTC by grugnog

Updating the distribution saving logic to handle the case of a distribution MIME type being updated.

fixes #3603 

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Switch to the 2.x branch
- [ ] Create a dataset using the remote URL https://download.medicaid.gov/data/newNADACPrice.csv
- [ ] Check the distribution mime type is `application/octet-stream`
- [ ] Run the import queue - no import should run
- [ ] Switch to this branch AND cherry pick the commit from #3613
- [ ] Create a new dataset using the remote URL https://download.medicaid.gov/data/newNADACPrice.csv
- [ ] Check the distribution mime type is now `text/csv`
- [ ] Run the import queue - the import should run and data should be available in preview

2021-08-11 03:28 UTC, janette commented
That works, I got a new record in dkan_metastore_resource_mapper table for the updated mimetype.

2021-08-11 14:25 UTC, dafeder commented
I think we should just reimport if the distribution has changed in any way, less field-specific, simpler...

2021-08-11 16:18 UTC, grugnog commented
@dafeder based on my testing, I think new distributions are already being created if any of the user editable fields change - I think the addition here is only needed because the MIME field is not purely user set, but has some additional detection logic that happens as part of the reference process.

2021-08-11 17:02 UTC, dafeder commented
@grugnog right -- new distributions are created on any JSON change but do not trigger a re-import. The motivation for suggesting this is that we really should be trying to keep fieldnames out of the DKAN code. We had made some progress on this in the spring and have definitely backslid a bit recently due to time pressure on just getting certain features working, but I think with any new code we merge we should think if there is an alternative with a reasonable LOE that would let us avoid adding more hardcoded field names in the codebase.

Another, probably better approach, would be to extend the new admin interface for chosing dataset properties that trigger a reimport (#3554) to do the same with distribution fields.

2021-08-14 13:43 UTC, dafeder commented
Have come back to this after reviewing and merging #3613 and now realize that the concerns I was raising here are really more specific to _that_ ticket, which we've merged for now anyway. We should go back to that at some point and abstract out all the distribution/field-specific stuff if possible, but this one is actually fine! 🙃

2021-08-14 14:18 UTC, dafeder commented
Rebased and tests were failing. Found a logic error, fixed.

2021-08-14 14:28 UTC, dafeder requested changes
Although we're getting a 100% score on coverage for the diff here, I don't feel the tests are sufficient. We manage to run all the new lines in our existing functional tests because the check for a changed mimetype in just being added as an OR condition to something that was already covered. We should have an additional test, preferably a unit test in ReferencerTest, that will check to see if a new distribution is triggered by changing the format but not  by changing another field (e.g. "title").

2021-08-20 03:41 UTC, merged