Get datastore query maximum row limit from config
GetDKAN/dkan pull request #3689
Opened 2021-10-07 15:31 UTC by janette

Allow site admins to set the maximum number of rows returned on a datastore query.

## QA Steps

- [ ] Visit /admin/dkan/sql-endpoint
- [ ] Set the value to something above 500
- [ ] Run a query with the limit set to the number you set in config
- [ ] Confirm the query works and is returning the expected number of rows

- [ ] Run a query with no limit specified
- [ ] Confirm it defaults to limit=500

- [ ] Run a query with the limit set to a number above the maximum value
- [ ] Confirm you get a JSON Schema validation failed error

## To Dos

- Add tests
- Move the config to live at `admin/dkan/datastore`
- Update documentation

2021-10-07 17:02 UTC, clayliddell requested changes
Just one minor suggestion; the PR otherwise looks good to merge.

2021-10-07 17:02 UTC, clayliddell commented on modules/datastore/src/Controller/QueryController.php
> +      $rows_limit = (int) $this->configFactory->get('datastore.settings')->get('rows_limit') ?: 500;
I think it would reducing confusion if we removed the default maximum of 500 specified here since it's already specified in the `$rows_limit` parameter in `Drupal\datastore\Service\DatastoreQuery::__construct()` (or vice versa, just ensure that it's occurring in one location).

2021-10-07 17:05 UTC, janette commented on modules/datastore/src/Controller/QueryController.php
> +      $rows_limit = (int) $this->configFactory->get('datastore.settings')->get('rows_limit') ?: 500;
sounds good

2021-10-07 17:10 UTC, clayliddell commented on modules/datastore/src/Service/DatastoreQuery.php
> +  public function __construct(string $json, int $rows_limit = 500) {
See https://github.com/GetDKAN/dkan/pull/3689#pullrequestreview-774168989.
```suggestion
  public function __construct(string $json, int $rows_limit) {
```

2021-10-07 17:14 UTC, merged

2021-10-11 13:45 UTC, dafeder commented
For future reference, ab963b8097e2b1e458ad1abeb42ba5b5c16c5740 was dropped in #3686, because changing the signature requirements for a public method makes this no longer backwards compatible.