Harvest drush options
GetDKAN/dkan pull request #3743
Opened 2022-01-21 22:52 UTC by dafeder

Adds some arguments to the `drush dkan:harvest:register` command so you don't have to use JSON.

JSON argument still works. But now you can create a standard Harvest plan by just passing `--identifier` and `--extract-uri`. All JSON properties do have an equivalent CLI option though that can be passed.

Also adds a JSON schema for harvest plans, but it's not being used for anything yet.

## QA Steps

2022-01-24 16:18 UTC, janette requested changes
@dafeder can you make the --extract-uri required as well. And maybe the schema should include the titles and required properties to match the one in the harvest repo https://github.com/GetDKAN/harvest/blob/master/schema/schema.json

2022-01-24 18:11 UTC, dafeder commented
> And maybe the schema should include the titles and required properties to match the one in the harvest repo 

Hah I totally missed that this existed. My schema is redundant, I'll just remove it.

2022-01-24 23:51 UTC, janette commented on modules/harvest/src/Commands/HarvestCommands.php
>     * @usage dkan-harvest:register '{"identifier":"example","extract":{"type":"\\Harvest\\ETL\\Extract\\DataJson","uri":"https://source/data.json"},"transforms":[],"load":{"type":"\\Drupal\\harvest\\L
update to @usage dkan:harvest:register

2022-01-26 21:40 UTC, dafeder commented
@janette see updates

2022-02-22 19:25 UTC, janette approved these changes

2022-02-22 19:26 UTC, merged