Prepend paths in api docs, based on $settings['dkan_api_base']
GetDKAN/dkan pull request #3745
Opened 2022-01-29 18:32 UTC by thierrydallacroce

Based on a user-defined `$settings['dkan_api_base']` value (i.e. `/provider-data`) in a `settings*.php` file, prepend that value to the API paths documentation.

- [x] Test coverage exists

2022-01-30 16:00 UTC, thierrydallacroce commented
@dafeder, this should be good to go. Let me know if you have any concerns or questions.
Thanks in advance.

2022-01-31 15:21 UTC, dafeder requested changes
Looks great just one inline documentation request

2022-01-31 15:21 UTC, dafeder commented on modules/common/src/DkanApiDocsGenerator.php
```suggestion

    // Add 'dkan_api_base' setting to prefix the API path if your routing does not start
    // with your site's root URL (e.g. "data" for API paths to use "/data/api/1").
```

2022-01-31 15:21 UTC, dafeder commented on modules/common/src/DkanApiDocsGenerator.php
@thierrydallacroce let's add a bit of explanation?

2022-02-07 19:52 UTC, dafeder approved these changes

2022-02-07 19:52 UTC, merged