Adding cypress tests for file upload
GetDKAN/dkan pull request #3749
Opened 2022-02-08 21:54 UTC by clayliddell

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

2022-02-08 23:28 UTC, clayliddell commented
@dafeder It looks like `sites/default/files` permissions is preventing the CSV file from being uploaded and causing the new test to fail. Have we figured out what's causing permission issues with that directory?

2022-02-09 00:17 UTC, dafeder commented
@clayliddell I don't think so; @dasumner was looking into it.

2022-02-22 16:56 UTC, dafeder requested changes
Remove baseUrl setting, and rename the remote file context

2022-02-22 17:00 UTC, clayliddell commented on cypress.json
> +  "baseUrl": "http://2x.localtest.me",
```suggestion
```

2022-02-22 17:00 UTC, clayliddell commented on cypress/integration/11_admin_dataset_file_upload.spec.js
> +  context('Create dataset with NetStorage upload', () => {
```suggestion
  context('Create dataset with remote file', () => {
```

2022-02-22 17:04 UTC, dafeder approved these changes

2022-02-22 17:13 UTC, merged