Add moderation state to admin dataset view. Add hide action to VBO.
GetDKAN/dkan pull request #3766
Opened 2022-03-15 13:57 UTC by janette

- Visit the /admin/dkan/datasets screen
- Confirm you can see the moderation state of the datasets in the table
- Confirm you can also use bulk operations to change multiple datasets to the hidden state

2022-03-24 20:34 UTC, dafeder requested changes

2022-03-24 20:34 UTC, dafeder commented on modules/metastore/modules/metastore_admin/src/Plugin/Action/HideCurrentRevisionAction.php
> + */
```suggestion
 * )
 *
 * @codeCoverageIgnore
 */
 Let's try not to get in trouble with code climate :)
```

2022-03-24 20:56 UTC, dafeder commented
@janette when trying the "hide" action I get a server error. Message is
```
Error: Call to undefined method Drupal\moderated_content_bulk_publish\AdminModeration::hide() in Drupal\metastore_admin\Plugin\Action\HideCurrentRevisionAction->execute() (line 41 of /var/www/dkan/modules/metastore/modules/metastore_admin/src/Plugin/Action/HideCurrentRevisionAction.php) 
```

2022-05-12 18:19 UTC, janette commented
**Remaining task:** 
Create a code coverage test for https://github.com/GetDKAN/dkan/blob/WCMS-8695/modules/metastore/modules/metastore_admin/src/Plugin/Action/HideCurrentRevisionAction.php


The new VBO option is tested in two Cypress tests but we need coverage that codeclimate will recognize.

2022-05-25 22:06 UTC, dafeder approved these changes

2022-05-25 22:06 UTC, merged