11948 Use pre-existing local file for import
GetDKAN/dkan pull request #3996
Opened 2023-08-01 22:29 UTC by paul-m

fixes [org/repo/issue#]

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

2023-08-22 20:17 UTC, dafeder requested changes
Amazing work here @paul-m. Take a look at a few suggestions and questions I had.

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +We want the resource_id of the distribution. Here’s an example of extracting it using jq:
```suggestion
We want the resource ID from the distribution. You can just select and copy it from the JSON output, or extract it using `jq <https://jqlang.github.io/jq/>`_:
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +These instructions assume you’ve already set up a dataset, either through the UI or by running a harvest or through the dataset API. We’ll need the ID of the existing dataset.
```suggestion
These instructions assume you’ve already created a dataset (through the the UI, a harvest or the API) that contains a distribution pointing to a remote CSV file, and that this CSV file has not yet been imported to the datastore. We’ll need the ID of the existing dataset.
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +It can help to download the files as a separate step from the import process, outside of the DKAN queue process. Then we can instruct DKAN to use those existing files for processing into the database
```suggestion
Very large datasets can present challenges for the datastore import process. What "very large" means will depend on your server infrastructure, but it's safe to say that when dealing with multi-gigabyte CSV files you may start to encounter broken file transfers or timeouts.

Because DKAN will make a local copy of a remote file in order to import it, it can help to prepare the import by transfering the files to the web server manually (or with shell scripts). Then you can instruct DKAN to use that already-existing local copy for processing into the database.
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +Abbreviated instructions. Read further for more details.
```suggestion
Below are some abbreviated instructions. Read past this section for details.
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +- Use :code:`drush dkan:datastore:prepare-localized [id]` to set up the local file directory.
```suggestion
- Use :code:`drush dkan:datastore:prepare-localized [resource_id]` to set up the local file directory.
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +- Transfer the file in some way other than a DKAN import.
```suggestion
- Transfer the file to that directory on the server using the command line or your file transfer program of choice.
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +- Tell DKAN to use local files with this configuration: :code:`drush config:set common.settings always_use_existing_local_perspective 1`
```suggestion
- Set DKAN to use existing local files for imports: :code:`drush config:set common.settings always_use_existing_local_perspective 1`
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +- Turn off the local file preference with configuration: :code:`drush config:set common.settings always_use_existing_local_perspective 0`
```suggestion
- Disable the local file configuration: :code:`drush config:set common.settings always_use_existing_local_perspective 0`
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +Now that we have the resource ID, we can tell DKAN to prepare for some other script or process to download the file. We use Drush to do this:
```suggestion
Now that we have the resource ID, we can tell DKAN expect some other process to download the file. We use :code:`drush dkan:datastore:prepare-localized` to do this:
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +We can pipe this to jq as well:
```suggestion
We can pipe this to jq as well, to extract the specific path where DKAN expects the file:
```

2023-08-22 20:17 UTC, dafeder commented on docs/source/user-guide/guide_local_files.rst
> +From the output of :code:`dkan:datastore:prepare-localized` we get the path. In our case this is :code:`/var/www/html/docroot/sites/default/files/resources/1fecf29222b12fc1ce2678abbc8f870f_1691778866
```suggestion
From the output of :code:`dkan:datastore:prepare-localized` we get the path. In our case this is */var/www/html/docroot/sites/default/files/resources/1fecf29222b12fc1ce2678abbc8f870f_1691778866*
```

2023-08-22 20:17 UTC, dafeder commented on modules/common/common.install
> +            'DKAN is configured to use localized files rather than download them during import.'
```suggestion
            'DKAN is configured to use localized files rather than download them during import.
            Disable this setting on the CLI by running: <code>drush config:set common.settings always_use_existing_local_perspective 0</code>'
```

2023-08-22 20:17 UTC, dafeder commented on modules/common/common.install
> +          'value' => 'always_use_existing_local_perspective: true',
```suggestion
```

2023-08-22 20:17 UTC, dafeder commented on modules/common/common.install
> +          'value' => 'always_use_existing_local_perspective: true',
Value is not required and this does not really add clarity

2023-08-22 20:17 UTC, dafeder commented on modules/common/src/DataResource.php
> -    $this->checksum = md5_file($this->filePath);
Can this get run on other perspectives? Is it possible that failing silently like this would have unexpected effects? Consider adding try/catch

2023-08-22 20:17 UTC, dafeder commented on modules/datastore/src/Drush.php
> -  protected function jobstorePrune($ref_uuid) {
What happened here? we don't need this anymore?

2023-08-22 20:55 UTC, paul-m commented on modules/common/common.install
> +          'value' => 'always_use_existing_local_perspective: true',
Only the value is displayed if you use `drush rq`

2023-08-22 20:58 UTC, paul-m commented on modules/datastore/src/Drush.php
> -  protected function jobstorePrune($ref_uuid) {
I looked and looked, and it's dead code.

2023-08-24 15:52 UTC, dafeder commented on modules/common/common.install
> +          'value' => 'always_use_existing_local_perspective: true',
Ah ok. Might be good to make it more human-readable at some point but not a blocker

2023-08-24 15:53 UTC, dafeder commented on modules/datastore/src/Drush.php
> -  protected function jobstorePrune($ref_uuid) {
Cool, nice catch.

2023-08-24 17:20 UTC, dafeder approved these changes
Approved, looks like we need to re-run a cypress test though

2023-08-24 17:35 UTC, merged