Compare with latest revision for changes for datastore_import
GetDKAN/dkan pull request #4002
Opened 2023-08-17 17:16 UTC by jastraat

DatastoreSubscriber::onPreReference compares the old version of the metadata to the new version of the metadata during dataset preSave and then queues a datastore_import and orphan_reference_processor queue items if there is a change.

However, it's using the node->original property which is incorrectly set to the last PUBLISHED revision of the node, not the LATEST revision. When using a publication workflow with draft datasets that are later published, this results in the datastore_import and being queued incorrectly when the dataset draft is published through the Drupal UI.

This PR is still a work in progress because the unit tests are not yet passing.

fixes [org/repo/issue#]

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

2023-09-18 16:23 UTC, jastraat commented
Unfortunately when testing this with PDC, PDC's custom publication approach is creating draft distributions on publish. ARGH. Possibly related to the fact that PDC is using the local url resource download url display, so this may be a unique problem when the last published version of a dataset had a different local url (e.g. an Acquia server).

2023-11-01 18:33 UTC, paul-m commented
I think we can mark the too-many-methods codeclimate error in NodeWrapper\Data as won't fix. Let's strategize about this and related workflow issues.

2023-12-08 18:27 UTC, janette approved these changes
This looks good to me. I'm not sure why the resource directories don't get removed but that is out of scope of the ticket.

2023-12-12 21:23 UTC, dafeder approved these changes
Looks good. I think there's just a lot going on in the metastore that shouldn't be necessary, but for now this appears to fix the pressing issues and improve test coverage. The cost is more complexity but I think its a good trade off to fix the draft workflow and we can think about a higher-level refactor later down the line.

2023-12-12 22:01 UTC, paul-m requested changes

2023-12-12 22:01 UTC, paul-m commented on modules/metastore/src/LifeCycle/LifeCycle.php
> +   * Orphan removed references if applicable.
This one-line description is unclear... Also the method name. Not sure what is triggered or whether it's responding to something being triggered.

2023-12-12 22:01 UTC, paul-m commented on modules/metastore/src/NodeWrapper/Data.php
> -  public function getOriginal() {
I realize we don't actually want node->original, but we should keep getOriginal() and mark it as deprecated with a suggestion as to what to do instead. If it weren't public, I wouldn't care as much.

2023-12-12 22:01 UTC, paul-m commented on modules/metastore/src/NodeWrapper/Data.php
> +      $node_storage = $this->entityTypeManager->getStorage('node');
Promote the node storage to a class property ($this->nodeStorage) that you grab in the constructor, so that we only have to dereference it once.

2023-12-12 22:01 UTC, paul-m commented on modules/metastore/src/NodeWrapper/Data.php
> +      $node_storage = $this->entityTypeManager->getStorage('node');
Promote the node storage to a class property ($this->nodeStorage).

2023-12-12 22:01 UTC, paul-m commented on tests/src/Functional/DatasetBTBTest.php
> +  public function testDraftWorkflowDistributionUrlLocalPerspective() {
What's the difference between this and testDraftWorkflowDistributionUrlSourcePerspective()? They both set a config and then run the same method, seemingly without different expectations... Should they behave differently? If the test is whether they behave the same, then runDraftWorkflowUpdateDistributionUrl() should be the test method with a dataprovider.

Similar for the other test methods here... many of them have the same expectation for different config.

2023-12-12 23:04 UTC, paul-m commented on tests/src/Functional/DatasetBTBTest.php
> +  public function testDraftWorkflowDistributionUrlLocalPerspective() {
This is a stylistic suggestion. Feel free to resolve, unless you really want to learn how to do @dataProvider. :-)

2023-12-13 14:58 UTC, jastraat commented on modules/metastore/src/LifeCycle/LifeCycle.php
> +   * Orphan removed references if applicable.
Renamed the function to be more clear.

2023-12-13 14:58 UTC, jastraat commented on modules/metastore/src/NodeWrapper/Data.php
> +      $node_storage = $this->entityTypeManager->getStorage('node');
Promoted!

2023-12-13 14:59 UTC, jastraat commented on tests/src/Functional/DatasetBTBTest.php
> +  public function testDraftWorkflowDistributionUrlLocalPerspective() {
Would love to learn, but perhaps in a later PR that refactors these tests..? :)

2023-12-13 14:59 UTC, jastraat commented on modules/metastore/src/NodeWrapper/Data.php
> +      $node_storage = $this->entityTypeManager->getStorage('node');
Promoted!

2023-12-13 15:00 UTC, jastraat commented on modules/metastore/src/NodeWrapper/Data.php
> -  public function getOriginal() {
Added back with deprecated annotation.

2023-12-13 16:12 UTC, paul-m approved these changes

2023-12-13 22:39 UTC, paul-m commented
Ran through a basic test run with OP and this branch seems OK.

2023-12-14 15:55 UTC, merged

2024-01-26 11:39 UTC, stefan-korn commented
Question about this change:

It seems to me since this change you can not edit the download URL of a distribution directly, but only via the dataset.

Am I right about that? Is that intended?

2024-01-26 17:01 UTC, janette commented
@stefan-korn correct, all user interaction is handled via the dataset form. The separate distribution node is a referenced artifact for use in the internal workings. Changing the downloadURL will generate a NEW distribution.