Issue #4036: Allow for an empty option in select fields via schema pr…
GetDKAN/dkan pull request #4037
Opened 2023-10-06 15:35 UTC by stefan-korn

fixes issue #4036 

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] add empty_value: true to dataset.json for "accessLevel"
- [ ] create or edit a dataset and note that there will be an empty option beside the real values "public", "restricted public", "non-public" if you open up the select
- [ ] if you save with the empty option the value should not exist in the json stored
- [ ] note that it does not really make sense for "accessLevel" to have it, but it suits as a demo

2023-10-06 15:42 UTC, dafeder commented
See my comment on the issue @stefan-korn, I think the proper behavior here is just to add an empty option in the select for any `enum` that is not required, and make sure the JSON that is produced does not contain the property.

2023-10-06 15:46 UTC, dafeder requested changes

2023-10-06 15:46 UTC, dafeder commented on modules/json_form_widget/src/StringHelper.php
> +        $element['#empty_value'] = '';
Looks like we're going a different direction anyway, but not sure where `$property->empty_value` is supposed to be getting set?

2023-10-06 15:58 UTC, stefan-korn commented on modules/json_form_widget/src/StringHelper.php
> +        $element['#empty_value'] = '';
I supposed it to be set in the schema .json file, just like "type", "format", etc. But yes now we are going a different and better way.

2023-10-06 18:24 UTC, dafeder commented
@stefan-korn do you feel up to updating the tests? I think you should be able to see the circleCI results and that the tests are all broken now... fairly trivial to update them to expect this and possibly to confirm the right result for both required and non-required fields, but if you're not familiar with PHPUnit let me know and we can help with that part.

2023-10-07 10:49 UTC, stefan-korn commented
I fixed the tests. The html output itself is not checked I suppose?

2024-07-03 13:40 UTC, dafeder approved these changes
Sorry I let this languish for so long @stefan-korn - just tested and it works perfectly.

2024-07-03 13:41 UTC, merged