Use the latest published dataset revision when returning results for the datastore query endpoint
GetDKAN/dkan pull request #4047
Opened 2023-10-27 16:17 UTC by jastraat

To recreate the error in a vanilla DKAN site:

- Create a published dataset with a distribution.
- Set the default moderation state to "draft".
- Edit the dataset and replace the distribution file with data that is recognizably different than the published version. Save as a draft.
- Run cron to do the imports
- Visit the dataset page in the site and confirm that the published version of the dataset is displayed.
- Use the datastore query endpoint {domain}/api/1/datastore/query/{dataset}/{index} and observe that the data returned is from the unpublished draft, not the published version.

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Create a published dataset with a distribution.
- [ ] Set the default moderation state to "draft".
- [ ] Edit the dataset and replace the distribution file with data that is recognizably different than the published version. Save as a draft.
- [ ] Run cron to do the imports
- [ ] Visit the dataset page in the site and confirm that the published version of the dataset is displayed.
- [ ] Use the datastore query endpoint {domain}/api/1/datastore/query/{dataset}/{index} and observe that the data returned is still from the published version.

2023-10-30 22:22 UTC, paul-m requested changes

2023-10-30 22:22 UTC, paul-m commented on modules/common/src/DatasetInfo.php
> +   *
How about adding a line here to explain the logic of what distribution id is returned based on published and draft scenarios?

2023-10-30 22:22 UTC, paul-m commented on modules/common/src/DatasetInfo.php
> +  public function getDistributionUuid(string $uuid, string $index = '0'): string {
Rename `$uuid` to `$dataset_uuid` please.

2023-10-30 22:22 UTC, paul-m commented on modules/common/src/DatasetInfo.php
> +    $metadata = $this->gather($uuid);
Similarly, rename `$metadata` to `$dataset_info` to match the docs from `gather()`, and the naming used in the test below.

2023-10-31 15:49 UTC, paul-m approved these changes

2023-11-01 04:21 UTC, dafeder approved these changes

2023-11-01 04:22 UTC, merged