Re-reference distributions on presave
GetDKAN/dkan pull request #4066
Opened 2023-11-20 22:36 UTC by jastraat

fixes [org/repo/issue#]

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

2023-11-21 17:47 UTC, dafeder requested changes
@jastraat we hit the code complexity gate because of adding a conditional nested inside another one, and actually in this case I don't think the conditional is needed at all. There is no error thrown if you unset a non-existent property. So in `Referencer::reference()` we can just call unset without checking if the Ref thing is there.

2023-11-21 17:52 UTC, jastraat commented
Updated to remove the check to see if the properties were set before unsetting -

2023-11-21 18:29 UTC, dafeder requested changes
This looks good, but as discussed we are going to hold off on merge until we at least have a functional test covering the changes to LifeCycle.

2023-12-05 17:11 UTC, jastraat commented
I'm going to go ahead and close this PR. All the changes in this PR have been included in the more comprehensive PR: https://github.com/GetDKAN/dkan/pull/4002 along with 5 new functional tests.

2023-12-05 17:11 UTC, closed without merging