#4068: Provide number widget
GetDKAN/dkan pull request #4069
Opened 2023-11-27 16:09 UTC by stefan-korn

fixes #4068

- [ ] Test coverage exists
- [ ] Documentation exists

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform to confirm that the feature or fix is working. Include as much details as possible so that the reviewer doesn't lose time figuring out how to perform steps.

2023-12-04 23:33 UTC, janette commented
@stefan-korn this would need test coverage before it can be merged.

2023-12-11 17:55 UTC, dafeder commented
@stefan-korn are you able to add some coverage? The easiest thing would probably be to add a number field to `Drupal\Tests\json_form_widget\Unit\JsonFormBuilderTest`

2023-12-11 22:02 UTC, dafeder requested changes
I think this will satisfy codeclimate about code/doc standards

2023-12-11 22:02 UTC, dafeder commented on modules/json_form_widget/src/WidgetRouter.php
> +   *   - max
```suggestion
   * @param object $spec
   *   Specification for UI options. Optional properties:
   *   - step: Ensures that the number is an even multiple of step.
   *   - min: Minimum value.
   *   - max: Maximum value.
```

2023-12-11 22:02 UTC, dafeder commented on modules/json_form_widget/src/WidgetRouter.php
> +   */
```suggestion
   * @return array
   *   The element configured as number.
   *
   * @see \Drupal\Core\Render\Element\Number
   */
```

2024-04-08 22:25 UTC, dafeder requested changes
@stefan-korn have given this another review. See my one comment here, I was able to cause an error by giving the ui schema a step but not a max.

I'd like to get this in, but I think it needs a little more work. Beyond the comments in this and previous reviews, I think it should also work to define a field as "number" directly in the schema, with no additional definition in the UI schema. This may mean adding a new "helper" class, or else consolidating "number" and "integer" since they ultimately use the same field type.

2024-04-08 22:25 UTC, dafeder commented on modules/json_form_widget/src/WidgetRouter.php
> +    if (isset($spec->step)) {
@stefan-korn shouldn't this be `$spec->max`?

2024-04-24 05:33 UTC, stefan-korn commented
@dafeder : I addressed your comments.

Regarding "number" in the schema. I wasn't aware that there is the integer field. It is only used once in the data-dictionary.json I suppose and we do not need data dictionary right now, so I missed that.

Should the schema be configurable about step, min and max? That way no widget "number" would be needed at all?

2024-07-03 13:24 UTC, dafeder commented
@stefan-korn re-thinking this I think the "number" field in the schema itself can be dealt with separately, should not be a blocker for this. I did a new PR from this that hits the test coverage, closing this in favor of #4215. Thanks!

2024-07-03 13:24 UTC, closed without merging