Add invalidateCacheTags to post_import queueworker
GetDKAN/dkan pull request #4125
Opened 2024-02-15 19:25 UTC by janette

Temporary fix for stale cache after post_import

## QA Steps

1. Set up vanilla site
2. ddev drush en sample_content
3. ddev drush dkan-sample-content:create
4. ddev drush dkan:datastore:import 3a187a87dc6cd47c48b6b4c4785224b7
5. Confirm datastore results: curl http://dkan.ddev.site/api/1/datastore/query/cedcd327-4e5d-43f9-8eb1-c11850fa7c55/0 
6. Confirm endpoint is cached: curl -I http://dkan.ddev.site/api/1/datastore/query/cedcd327-4e5d-43f9-8eb1-c11850fa7c55/0 , look for x-drupal-cache: HIT
7. ddev drush queue:run post_import
8. Confirm endpoint is now not cached: curl -I http://test1.ddev.site/api/1/datastore/query/cedcd327-4e5d-43f9-8eb1-c11850fa7c55/0 , x-drupal-cache should be MISS or simply not present

2024-02-20 20:24 UTC, dafeder commented on modules/datastore/src/Plugin/QueueWorker/PostImportResourceProcessor.php
> +    $this->invalidateCacheTags($id . '__' . $version . '__source');
```suggestion
    if ($postImportResult->getStatus() === Result::DONE) {
      $this->invalidateCacheTags(DataResource::buildUniqueIdentifier(
        $data->getIdentifier(),
        $data->getVersion
        DataResource::DEFAULT_SOURCE_PERSPECTIVE
      );
    }
```

2024-02-20 20:25 UTC, dafeder requested changes

2024-02-20 20:25 UTC, dafeder commented on modules/datastore/src/Plugin/QueueWorker/PostImportResourceProcessor.php
> +    $this->invalidateCacheTags($id . '__' . $version . '__source');
I think we should make sure the job completed correctly like we do in the import queue worker? Also might as well use existing code to construct the identifier string no?

2024-02-20 20:40 UTC, janette commented on modules/datastore/src/Plugin/QueueWorker/PostImportResourceProcessor.php
> +    $this->invalidateCacheTags($id . '__' . $version . '__source');
@dafeder RE: _make sure the job completed_ meaning add a switch ($status) block?

2024-02-22 03:48 UTC, dafeder approved these changes

2024-02-22 03:48 UTC, merged