Update the dataset.ui.json schema file
GetDKAN/dkan pull request #4164
Opened 2024-04-17 00:28 UTC by janette

Schema update mentioned in #4067

2024-04-17 16:36 UTC, dafeder commented
@janette see https://github.com/GetDKAN/dkan/pull/4067#issuecomment-1830392295

I think we should not make this change to core dataset.ui.json?

2024-04-17 16:37 UTC, dafeder requested changes
See convo

2024-04-25 15:25 UTC, janette commented
@dafeder revised to update the docs instead

2025-03-10 16:21 UTC, dafeder approved these changes
Updated with a few tweaks, approved

2025-03-10 16:21 UTC, merged