WCMS-20047: Data Dictionary Documentation
GetDKAN/dkan pull request #4271
Opened 2024-09-03 20:12 UTC by rovcase

Fixes [issue#]

## Describe your changes

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform. Be as specific as possible, provide examples if appropriate.

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [ ] I have updated or added documentation

2024-09-05 21:00 UTC, dmundra requested changes
@rovcase looking good. Left you comments to consider for the data dictionary page. Let me know what you think.

2024-09-05 21:00 UTC, dmundra commented on docs/source/user-guide/guide_data_dictionaries.rst
> +5. An "Add new field" editable form box will appear. Complete the required form fields here, reference the Table Schema section above if needed.
Nitpick, quote the 'Table Schema' and link it to that header in the page?

2024-09-05 21:00 UTC, dmundra commented on docs/source/user-guide/guide_data_dictionaries.rst
> +    :alt: A portion of the data dictionary creation admin page with a focus on the "Add new field" section.
Love the alt text. Thank you!

2024-09-05 21:00 UTC, dmundra commented on docs/source/user-guide/guide_data_dictionaries.rst
> +10.  Clicking the gear icon will open an editable form that will show the previously entered information for the respective data dictionary field. You can then modify this information and either: sav
I would maybe quote the 'save', 'cancel', and 'delete' or at least title case it. Nit pick though.

2024-09-05 21:00 UTC, dmundra commented on docs/source/user-guide/guide_data_dictionaries.rst
> +10.  Clicking the gear icon will open an editable form that will show the previously entered information for the respective data dictionary field. You can then modify this information and either: sav
This will match the indexes section where you use double quotes and title case.

2024-09-06 15:51 UTC, rovcase commented on docs/source/user-guide/guide_data_dictionaries.rst
> +5. An "Add new field" editable form box will appear. Complete the required form fields here, reference the Table Schema section above if needed.
Good call, fixed. Thanks!

2024-09-06 15:52 UTC, rovcase commented on docs/source/user-guide/guide_data_dictionaries.rst
> +10.  Clicking the gear icon will open an editable form that will show the previously entered information for the respective data dictionary field. You can then modify this information and either: sav
Agreed, ty. Updated!

2024-09-06 16:05 UTC, rovcase commented
> @rovcase looking good. Left you comments to consider for the data dictionary page. Let me know what you think.

Tysm for the look over, added your changes and should be good now.

2024-09-06 17:39 UTC, dmundra commented on docs/source/user-guide/guide_data_dictionaries.rst
> +10.  Clicking the gear icon will open an editable form that will show the previously entered information for the respective data dictionary field. You can then modify this information and either: sav
@rovcase Cancel and delete look good but there seems to be an extra line break now after "Cancel" and also need to apply the same change to "Save".

2024-09-06 17:40 UTC, dmundra commented
> > @rovcase looking good. Left you comments to consider for the data dictionary page. Let me know what you think.
> 
> Tysm for the look over, added your changes and should be good now.

Thank you @rovcase. I think one more fix (I left a reply on a previous comment) and you should be good to go.

2024-09-06 18:22 UTC, merged