WCMS-22404: Dictionary-Widget: Streamline the button labels for the Index and Index Fields
GetDKAN/dkan pull request #4315
Opened 2024-10-14 16:22 UTC by rovcase

## Describe your changes
Updates labels for Data Dictionary Widget

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform. Be as specific as possible, provide examples if appropriate.

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [ ] I have updated or added tests to cover my code
- [ ] I have updated or added documentation

2024-10-23 23:07 UTC, janette requested changes
Looks great @rovcase just some minor doc changes please.

2024-10-23 23:07 UTC, janette commented on docs/source/user-guide/guide_indexes.rst
>   b. Length: how many characters long this field can be.
Length: The number of characters of the column you want to index. Indexing only a prefix of column values in this way can make the index file much smaller.

2024-10-23 23:07 UTC, janette commented on docs/source/user-guide/guide_indexes.rst
> +7. After defining the index fields, click "Save index" to save the index temporarily. Remember that the Data Dictionary and it's respective fields and indexes are not completely saved until the form
...until the form is submitted by clicking "Save" at the bottom of the screen.

2024-10-23 23:07 UTC, janette commented on docs/source/user-guide/guide_indexes.rst
>  8. Note that after submitting, an informational table will appear listing the indexes you have created thus far and their names, types, and fields (field name and field length).
8. Note that after saving the index, an informational table will appear...

(The button is "save index" so let's be consistent)

2024-10-23 23:07 UTC, janette commented on docs/source/user-guide/guide_indexes.rst
>        :alt: A portion of the data dictionary creation admin page with a focus on the edit index box.
line 136, small tweak to the first sentence:
Note that once you have saved an index, it is not possible to edit the fields within the index at this time. ...

2024-10-24 15:12 UTC, rovcase commented on docs/source/user-guide/guide_indexes.rst
>        :alt: A portion of the data dictionary creation admin page with a focus on the edit index box.
Sounds good, change made ty!

2024-10-24 15:13 UTC, rovcase commented
All look good ty for the suggested changed! Last three commits should add everything suggested. Thanks again!

2024-10-24 15:27 UTC, closed without merging