4336: Return 400 error on invalid JSON sent to the datastore API
GetDKAN/dkan pull request #4341
Opened 2024-11-15 01:52 UTC by janette

Fixes #4336

## Describe your changes
Better response for invalid JSON

## QA Steps

- [ ] Run the following POST
```
POST https://demo.getdkan.org/api/1/datastore/query/cedcd327-4e5d-43f9-8eb1-c11850fa7c55/0 HTTP/1.1

{
  "conditions": [
}
```
- [ ] Confirm you get a 400 error and "Invalid JSON" message

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [ ] I have updated or added tests to cover my code
- [ ] I have updated or added documentation

2024-11-15 19:49 UTC, paul-m requested changes

2024-11-15 19:49 UTC, paul-m commented on modules/datastore/src/Controller/AbstractQueryController.php
>    protected function buildDatastoreQuery(Request $request, mixed $identifier = NULL) {
`\Drupal\datastore\Controller\QueryDownloadController::buildDatastoreQuery()` overrides this... Both call `getPayloadJson()` which is probably where we should throw the exception.

So: Move this checking to either `getPayloadJson()` or `fixTypes()`, and add a bad JSON test for both query controller and download query controller.

2025-01-14 19:29 UTC, kaise-lafrai commented on modules/datastore/src/Controller/AbstractQueryController.php
>    protected function buildDatastoreQuery(Request $request, mixed $identifier = NULL) {
Done

2025-01-14 20:15 UTC, paul-m requested changes

2025-01-14 20:15 UTC, paul-m commented on modules/datastore/src/Controller/AbstractQueryController.php
> +    if ($data === NULL) {
I'd suggest
```
  public static function fixTypes($json, $schema) {
    if ($data = json_decode($json) !== NULL) {
      $validator = new Validator();
      $validator->coerce($data, json_decode($schema));
      return json_encode($data, JSON_PRETTY_PRINT);
    }
    throw new \InvalidArgumentException("Invalid JSON");
  }
```
...or similar so that we don't create a `Validator` unless we need to.

2025-01-14 22:26 UTC, paul-m approved these changes

2025-01-14 22:31 UTC, merged