Some fixes for Drupal 11.0.x compatibility
GetDKAN/dkan pull request #4354
Opened 2024-12-09 15:19 UTC by dafeder

Fixes #4356 

Fixes to get DKAN build-able and passing with Drupal 11.0. I still haven't gotten the CI to work, because mysql 8.0, at least in ddev, doesn't allow the db user to turn off strict mode. MariaDB works fine. Need to decide whether to fix what's going on in mysql or switch to mariadb somehow in CI. But I'd like to get these changes in before they get stale. 

The circleCI changes ended up not being needed since I couldn't get the Drupal 11 job to run anyway, but I left them in because they're probably useful in the future.

To test Drupal 11:

1. `ddev config --auto`, `ddev get getdkan/ddev-dkan`
2. Edit config.dkan.yml, change database to mariadb 10.6, php version to 8.3.
3. `ddev dkan-init --project-version=11.0.x`
4. `ddev dkan-site-install`
5. `ddev dkan-phpunit`

Changes of note:

* Full removal of Drupal's ContainerAwareEventDispatcher
* Full removal of DKAN's LoggerTrait
* Many PHPUnit data provider functions changed to be abstract
* Replaced many calls to getMockForAbstractClass to simply getMock() due to deprecation. This also meant mocking, for instance, SQLite connection class instead of just the abstract connection class.
* No more use of StatementWrapper in Drupal queries

2024-12-10 21:05 UTC, dafeder commented
Update: as of last push, fixed many errors, but still getting some from:

* Drupal\Tests\dkan_js_frontend\Unit\SimpleSitemapArbitraryLinksAlterTest
* Drupal\Tests\metastore_search\Unit\SearchTest
* Drupal\Tests\metastore\Kernel\DataDictionarySettingsFormTest
* Drupal\Tests\metastore\Unit\MetastoreServiceTest

Also will need 
* to re-run with `--display-phpunit-deprecations` to make sure there are no more of those
* search whole repo for `getMockForAbstractClass()` which should really be replaced now
* check for other deprecations in linter

2024-12-12 04:12 UTC, dafeder commented
Only test failing at this point seems to be `AdminDatasetFileUploadTest::testCreateDatasetWithFileUpload()`. I think this is related to something wrong with select2; I also see issues with the form when loading in my browser. May put this aside until there is a proper select2 release for D11.

2024-12-19 16:00 UTC, dafeder commented
Another option, probably better - once all tests pass, revert changes to info.yml files and merge this, so that the fixes don't get stale.

2025-01-30 19:17 UTC, paul-m requested changes
We should update the tests on https://github.com/GetDKAN/recommended-project/tree/11.0.x since we don't need PHP 8.1 or PHP 8.2 any more.

2025-01-30 19:17 UTC, paul-m commented on composer.json
> +        "guzzlehttp/guzzle": "^6.5.8 || ^7",
We definitely want to exclude guzzle < 7.4.5 because https://nvd.nist.gov/vuln/detail/CVE-2022-31091

2025-01-30 19:30 UTC, dafeder commented on composer.json
> +        "guzzlehttp/guzzle": "^6.5.8 || ^7",
Fixed

2025-01-30 20:06 UTC, paul-m requested changes

2025-01-30 20:06 UTC, paul-m commented on modules/datastore/tests/src/Kernel/Service/PostImportTest.php
> +use Drupal\Core\Database\Query\SelectInterface;
My IDE tells me these changes are unneeded.

2025-01-30 20:06 UTC, paul-m commented on modules/datastore/tests/src/Unit/Controller/QueryControllerTest.php
> +use Symfony\Component\EventDispatcher\EventDispatcher;
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher is now an unneeded use.

2025-01-30 20:06 UTC, paul-m commented on modules/datastore/tests/src/Unit/Controller/QueryDownloadControllerTest.php
> +use Symfony\Component\EventDispatcher\EventDispatcher;
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher is now an unneeded use.

2025-01-30 20:10 UTC, paul-m commented
I guess we still need to add D11 to the testing matrix.

2025-02-04 20:41 UTC, dafeder commented
Believe I have addressed everything @paul-m

2025-02-04 21:30 UTC, paul-m approved these changes

2025-02-04 21:30 UTC, merged