Factor our DatastoreResource class
GetDKAN/dkan pull request #4372
Opened 2024-12-27 22:26 UTC by dafeder

Fixes #4359

## Describe your changes

Remove DatastoreResource class, use DataResource for everything

## QA Steps

- [ ] Add manual QA steps in checklist format for a reviewer to perform. Be as specific as possible, provide examples if appropriate.

## Checklist before requesting review

_If any of these are left unchecked, please provide an explanation_

- [ ] I have updated or added tests to cover my code
- [ ] I have updated or added documentation

2024-12-27 22:27 UTC, dafeder commented
Currently debugging failing MySqlQueryDownloadControllerTest. It fails at `AbstractDatabaseTable::setTable()`, I think something is making the perspective be `local_file` when it should be something else? It can't get a schema anyway.

2024-12-30 23:21 UTC, dafeder commented
Some progress. Need to redo QueryDownloadControllerTest somehow... not so easy to use fake resource names because table name is no longer based on an ID in the DatastoreResource class that we can simply control via the constructor.

2025-01-07 20:59 UTC, dafeder commented on modules/json_form_widget/tests/src/Unit/StringHelperTest.php
> -    print_r($result['#default_value']);
Not sure how this crept in here!

2025-01-07 21:55 UTC, paul-m requested changes
`Drupal\Tests\datastore\Unit\Storage\DatabaseTableFactoryTest` still creates a `DatastoreResource`.

2025-01-07 21:56 UTC, paul-m requested changes
Let's add to the docblock of `Drupal\datastore\Storage\DatabaseTableFactory::getInstance()` that the resource must be a DataResource object.

2025-01-07 21:58 UTC, paul-m requested changes
`Drupal\Tests\datastore\Unit\Plugin\QueueWorker\ImportJobTest` spends a lot of time making `DatastoreResource` objects.

2025-01-07 22:10 UTC, paul-m requested changes

2025-01-07 22:10 UTC, paul-m commented on modules/datastore/modules/datastore_mysql_import/src/Service/MysqlImport.php
> +      return $this->setResultError(sprintf(
Needs test coverage, since we might be inadvertently modifying the logic.

2025-01-07 22:10 UTC, paul-m commented on modules/common/tests/src/Unit/DataResourceTest.php
> -  /**
We should leave this test because even though it covers deprecated code, the code is still there.

2025-01-07 22:16 UTC, dafeder commented on modules/common/tests/src/Unit/DataResourceTest.php
> -  /**
I was having trouble getting the test to work and thought it was maybe not worth it but I'll give it another shot

2025-01-08 21:12 UTC, dafeder commented on modules/datastore/modules/datastore_mysql_import/src/Service/MysqlImport.php
> +      return $this->setResultError(sprintf(
After some discussion, this seems outside the scope of this PR. We will do a follow-up to cover this line, and maybe make it more consistent across the two ImportJob classes.

2025-01-08 21:50 UTC, dafeder commented on modules/common/tests/src/Unit/DataResourceTest.php
> -  /**
Actually it just works as is, I'm not sure why this was removed tbh! Restored.

2025-01-08 21:58 UTC, dafeder commented
> Let's add to the docblock of `Drupal\datastore\Storage\DatabaseTableFactory::getInstance()` that the resource must be a DataResource object.

@paul-m see 2594e68

2025-01-08 22:11 UTC, paul-m approved these changes

2025-01-14 14:27 UTC, dafeder commented
Putting back to draft, needs a bit more testing from @janette

2025-01-16 14:25 UTC, dafeder commented
Update from @janette: we're good to go

2025-01-16 15:46 UTC, janette approved these changes

2025-01-16 15:47 UTC, merged